"""
ChargeFlow AI V2 — LLM Provider Abstraction
=============================================
Abstract provider interface for LLM text generation.

Implementations:
  1. GeminiLLMProvider: Calls Google Gemini API via httpx REST endpoint.
     Requires GEMINI_API_KEY environment variable or Streamlit secrets.
  2. MockLLMProvider: Deterministic, offline mock provider for UNIT TESTS ONLY.

Rule:
  MockLLMProvider is ONLY used when explicitly injected by tests.
  In production/runtime application, if no real LLM API key is present,
  the system MUST report that answer generation is unavailable rather than
  silently using MockLLMProvider.
"""

import os
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
import httpx


class LLMProvider(ABC):
    """
    Abstract LLM provider interface.
    """

    @abstractmethod
    def generate(self, prompt: str, system_instruction: str) -> str:
        """
        Generates text output given prompt and system_instruction.
        """
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """
        Returns True if the provider is configured and ready for calls.
        """
        pass


class GeminiLLMProvider(LLMProvider):
    """
    Google Gemini REST API implementation using httpx.
    """

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-1.5-flash"):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model_name = model_name
        self.endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent"

    def is_available(self) -> bool:
        return bool(self.api_key and self.api_key.strip())

    def generate(self, prompt: str, system_instruction: str) -> str:
        if not self.is_available():
            raise RuntimeError(
                "Gemini API key is not configured. Set GEMINI_API_KEY environment variable."
            )

        url = f"{self.endpoint}?key={self.api_key}"
        payload = {
            "contents": [
                {
                    "parts": [{"text": f"SYSTEM INSTRUCTIONS:\n{system_instruction}\n\nUSER PROMPT:\n{prompt}"}]
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 800,
            }
        }

        try:
            with httpx.Client(timeout=10.0) as client:
                response = client.post(url, json=payload)
                if response.status_code != 200:
                    raise RuntimeError(f"Gemini API Error {response.status_code}: {response.text}")

                data = response.json()
                candidates = data.get("candidates", [])
                if not candidates:
                    return "No answer generated by Gemini API."

                parts = candidates[0].get("content", {}).get("parts", [])
                if not parts:
                    return "Empty content returned by Gemini API."

                return parts[0].get("text", "").strip()
        except Exception as exc:
            raise RuntimeError(f"Failed to communicate with Gemini LLM API: {exc}") from exc


class MockLLMProvider(LLMProvider):
    """
    Mock LLM provider used EXPLICITLY IN UNIT TESTS.
    Never used in runtime application fallback.
    """

    def __init__(self, mock_responses: Optional[Dict[str, str]] = None):
        self.mock_responses = mock_responses or {}

    def is_available(self) -> bool:
        return True

    def generate(self, prompt: str, system_instruction: str) -> str:
        prompt_lower = prompt.lower()
        for key, resp in self.mock_responses.items():
            if key.lower() in prompt_lower:
                return resp

        if "feature" in prompt_lower or "model" in prompt_lower:
            return "Based on the evidence, ChargeFlow AI uses 16 pre-engineered features in its RandomForest demand forecaster."
        elif "utilization" in prompt_lower or "india" in prompt_lower:
            return "Based on the evidence, average charger utilization in India is 23%, compared to the 65% benchmark."
        else:
            return "Based on the provided evidence snippets, ChargeFlow AI is an intelligent EV charging orchestration platform."
